<a href="https://colab.research.google.com/github/AbdelnasserMostafa/-myproject/blob/master/100_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Reference: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.md

In [ ]:
# This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy 
# documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a 
# set of exercises for those who teach.

# If you find an error or think you've a better way to solve some of them, feel free to open an issue at
# https://github.com/rougier/numpy-100

In [ ]:
# 1. Import the numpy package under the name np

import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration

print(np.__version__)
np.show_config()

1.14.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
# 3. Create a null vector of size 10

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. How to find the memory size of any array?

Z = np.zeros((10, 10))
print('%d bytes' % (Z.size * Z.itemsize))

800 bytes


In [ ]:
# 5. How to get the documentation of the numpy add function from the comman line?

%run 'python -C "inport numpy; numpy.info(numpy.add)"'

ERROR:root:File `'python -C "inport numpy; numpy.info(numpy.add)".py'` not found.


In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1

Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Create a vector with values ranging from 10 to 49

Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last)

Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8

Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
# 11. Create a 3x3 identity matrix

Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 12. Create a 3x3x3 array with random values

Z = np.random.random((3,3,3))
print(Z)

[[[0.88761779 0.61430757 0.75578568]
  [0.25932005 0.00952632 0.26513548]
  [0.63439178 0.02537388 0.83530201]]

 [[0.52554773 0.36838704 0.29313099]
  [0.96932679 0.0525967  0.30358949]
  [0.08527143 0.66585194 0.78255896]]

 [[0.59844677 0.55298979 0.82995324]
  [0.63342606 0.6137553  0.40466476]
  [0.38938889 0.89195237 0.09476187]]]


In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values

Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print('Minimum Value: ', Zmin)
print('Maximum Value: ', Zmax)



Minimum Value:  0.0157977441924686
Maximum Value:  0.9999090795014783


In [ ]:
# 14. Create a random vector of size 30 and find the mean value

Z = np.random.random(30)
m = Z.mean()
print(m)

0.4701257045908227


In [ ]:
# .15 Create a 2d array with 1 on the border and 0 inside

Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# .16 How to add a border (filled with 0's) around an existing array?

Z = np.ones((10, 10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# .17 What is the result of the following expression?

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
# 18. Create a 5x5 matrix values 1,2,3,4 just below the diagonal

Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard patterh

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x, y, z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function

Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 22. Normalize a 5x5 random matrix

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.63063891 -0.06700242 -0.48615906  0.98615022 -0.79216177]
 [-0.60067366 -0.04741761 -1.29428565 -1.04382818 -1.20167258]
 [-0.64083935  1.77627548  1.66293846  0.74884018 -0.63391111]
 [ 0.65994731 -0.76035439 -1.13117849  0.48922977  0.39525759]
 [ 0.30946237  0.23476316 -1.2615815  -0.81407213  1.88163443]]


In [ ]:
# 23. Create a custom dtype that describes a color as four unsigned bytes(RGBA)

color = np.dtype([('r', np.ubyte, 1),
                 ('g', np.ubyte, 1),
                 ('b', np.ubyte, 1),
                 ('a', np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# 26. What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?

#Z**Z          # Not a legal expression
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z         # Not a legal expression

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

In [ ]:
# 28. What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


In [ ]:
# 29. How to round away from zero a float array?
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-1. -8. -6. -8. 10.  3. -8. -3. -6. -2.]


In [ ]:
# 30. How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 6 7 8]


In [ ]:
# 31. How to ignore all numpy warnings (not recommended)?

# Suicide mode on
defaults = np.seterr(all='ignore')
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [ ]:
# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
  Z = np.ones(1) / 0

In [ ]:
# 32. Is the following expression true?

np.sqrt(-1) == np.emath.sqrt(-1)

False

In [ ]:
# 33. How to get the dates of yesterday, today, and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-01-05
2019-01-06
2019-01-07


In [ ]:
# 34. How to get all the dates corresponding to the month of July 2016?

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# 35. How to compute((A+B)*(-A/2)) in place(without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

In [ ]:
# 36. Extract the integer part of a random array using 5 different methods.

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[7. 5. 2. 2. 9. 4. 7. 1. 9. 4.]
[7. 5. 2. 2. 9. 4. 7. 1. 9. 4.]
[7. 5. 2. 2. 9. 4. 7. 1. 9. 4.]
[7 5 2 2 9 4 7 1 9 4]
[7. 5. 2. 2. 9. 4. 7. 1. 9. 4.]


In [ ]:
# 37. Create a 5x5 matrix with row value ranging from 0 to 4.

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# 38. Consider a generator function that generates 10 integers and use it to build an array.

def generate():
  for x in range(10):
    yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded.

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# 40. Create a random vector of size 10 and sort it.

Z = np.random.random(10)
Z.sort()
print(Z)

[0.03681298 0.15348244 0.29919    0.3532031  0.48369204 0.60506448
 0.70567768 0.76815049 0.89552161 0.98075202]


In [ ]:
# 41. How to sum a small array than np.sum?
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

In [ ]:
# 42. Consider two random array A and B, check if they are equal.

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values no tolerence (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [ ]:
# 43. Make an array immutable (read-only).

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

Z = np.random.random((10, 2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.01188139 0.89083418 0.79705998 0.37484308 0.78343568 1.08548049
 0.73641538 1.01986216 0.72072215 0.91577372]
[0.34303204 0.28647093 1.22991196 0.29842132 0.78401001 0.94471198
 0.96746145 0.75926659 1.37795492 0.86910241]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.2547219  0.         0.52814911 0.59735263 0.60724688 0.4450062
 0.44478537 0.08870526 0.04349877 0.54978547]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C(Cij =1/(xi - yj))
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scalar type.

for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# 49. How to print all the values of an array

np.set_printoptions(threshold=np.nan)
Z = np.zeros((16, 16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 50. How to find the colosest value (to a given scalar) in a vector?

Z = np.arange(100)
V = np.random.uniform(0, 100)
index = (np.abs(Z-V)).argmin()
print(Z[index])

4


In [ ]:
# 51. Create a structured array representing a position(x,y) and color(r,g,b)

Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)
                  

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [ ]:
# 52. Consider a random vector with shape (100, 2) representing coordinates, find point by point distances

Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.42885022 0.50304387 0.52634184 0.78174213 0.45604521
  0.30265828 0.47829555 0.4299435  0.27196193]
 [0.42885022 0.         0.16946478 0.32848937 0.3558552  0.73669541
  0.15991971 0.51712606 0.04823667 0.59709714]
 [0.50304387 0.16946478 0.         0.17734885 0.31967382 0.70103412
  0.30637154 0.41829599 0.12450926 0.59688744]
 [0.52634184 0.32848937 0.17734885 0.         0.45393306 0.59474505
  0.42705852 0.27002499 0.28026284 0.53291488]
 [0.78174213 0.3558552  0.31967382 0.45393306 0.         1.02036886
  0.50857463 0.7215368  0.3523246  0.9131665 ]
 [0.45604521 0.73669541 0.70103412 0.59474505 1.02036886 0.
  0.68619995 0.346232   0.70888582 0.18464286]
 [0.30265828 0.15991971 0.30637154 0.42705852 0.50857463 0.68619995
  0.         0.54295681 0.18798662 0.52239261]
 [0.47829555 0.51712606 0.41829599 0.27002499 0.7215368  0.346232
  0.54295681 0.         0.4751604  0.34816023]
 [0.4299435  0.04823667 0.12450926 0.28026284 0.3523246  0.70888582
  0.18798662 0.4751604

In [ ]:
# Much faster with Scipy

import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.81588116 0.78225878 0.79342858 0.66471352 0.70609621
  0.12087727 0.82912881 0.64630242 0.45708817]
 [0.81588116 0.         0.31409996 0.29753113 0.4871919  0.38116988
  0.7805268  0.88377236 0.38052278 0.41607584]
 [0.78225878 0.31409996 0.         0.02100278 0.21261869 0.63709355
  0.70426424 0.58492896 0.14739192 0.32636794]
 [0.79342858 0.29753113 0.02100278 0.         0.2333937  0.6277961
  0.71755886 0.60528191 0.16445423 0.33665434]
 [0.66471352 0.4871919  0.21261869 0.2333937  0.         0.73214717
  0.56614463 0.39882385 0.11038345 0.26270111]
 [0.70609621 0.38116988 0.63709355 0.6277961  0.73214717 0.
  0.73016317 1.11512539 0.62627716 0.52251094]
 [0.12087727 0.7805268  0.70426424 0.71755886 0.56614463 0.73016317
  0.         0.70857907 0.56192447 0.38868172]
 [0.82912881 0.88377236 0.58492896 0.60528191 0.39882385 1.11512539
  0.70857907 0.         0.50888664 0.60128795]
 [0.64630242 0.38052278 0.14739192 0.16445423 0.11038345 0.62627716
  0.56192447 0.508886

In [ ]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# How to read the following file?

from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [ ]:
# 55. What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# 56. Generate a generic 2D Gaussian-like array

import numpy as np

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
# 57. How to randomly place p elements in a 2D array?
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# 58. Subtract the mean of each row of a matrix.
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.30004139 -0.02790917 -0.36575245 -0.29615618  0.36573422  0.20444547
   0.25765407 -0.00868743 -0.18229831  0.35301117]
 [ 0.20589744  0.12642899 -0.06606854  0.36662437  0.2758665  -0.39836993
  -0.27369525  0.35642668 -0.58859902 -0.00451126]
 [ 0.05300886 -0.35072224  0.37593585  0.50125718  0.26930833 -0.08792212
  -0.12940547  0.06966247 -0.3727926  -0.32833027]
 [-0.22812769 -0.00565641  0.31118718 -0.42303761 -0.01174177 -0.05352086
  -0.08344151  0.21085099 -0.0444271   0.32791478]
 [-0.51810041 -0.23041858 -0.38680887  0.14340295 -0.04454819  0.43607311
   0.2108065   0.14557626  0.3985707  -0.15455347]]


In [ ]:
# 59. How to sort an array by the nth column?
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print()
print(Z[Z[:,1].argsort()])

[[2 9 4]
 [7 6 2]
 [7 2 7]]

[[7 2 7]
 [7 6 2]
 [2 9 4]]


In [ ]:
# 60. How to tell if a given 2D array has null columns?
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [ ]:
# 61. Find the nearest value from a given value in an array

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5289062463042858


In [ ]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# 63. Create an array class that has a name attribute

class NamedArray(np.ndarray):
  def __new__(cls, array, name='no name'):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', 'no name')
    
Z = NamedArray(np.arange(10), 'range_10')
print(Z.name)

range_10


In [ ]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 1. 2. 5. 3. 1. 3. 6. 3.]


In [ ]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list(I)?
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
# 66. Considering a (w,h,3) image of dtype=ubyte, compute the number of unique colors
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))
print(np.unique(F))
print(np.unique(n))

[0 1]
[  0   1 256 257]
[4]


In [ ]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

A = np.random.randint(0,10,(3,4,3,4))
# Solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2, -1))
print(sum)
print()

# Solutiong by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 42 57 65]
 [51 64 59 67]
 [31 42 43 54]]

[[52 42 57 65]
 [51 64 59 67]
 [31 42 43 54]]


In [ ]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size
# describing subset indices?
# Author: Jaime Fernandez del Rio

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print()

# Pandas solution as reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.44879532 0.49494299 0.45730336 0.53982461 0.34021102 0.47344753
 0.59223577 0.52023352 0.51123321 0.50070744]

0    0.448795
1    0.494943
2    0.457303
3    0.539825
4    0.340211
5    0.473448
6    0.592236
7    0.520234
8    0.511233
9    0.500707
dtype: float64


In [ ]:
# 69. How to get the diagonal of a dot product?
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum('ij,ji->', A, B)

7.854309222732696

In [ ]:
# 70. Consider the vector [1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each value
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
# 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions(5,5)

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
# 72. How to swap two rows of an array?
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# 73. Consider a set of 10 triplets describing 10 traingles (with shared vertices), find the set of unique line 
# segment composing all the triangles
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 8, 12) ( 8, 81) (10, 15) (10, 37) (12, 81) (13, 16) (13, 95) (14, 80)
 (14, 97) (15, 37) (16, 25) (16, 95) (20, 56) (20, 82) (25, 95) (40, 53)
 (40, 62) (41, 76) (41, 91) (47, 52) (47, 67) (52, 67) (53, 62) (55, 65)
 (55, 71) (56, 82) (65, 71) (76, 91) (80, 97)]


In [ ]:
# 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
# Author: Jaime Fernandez del Rio

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
# 75. How to compute averages using a sliding window over an array?
# Author: Jaime Fernandes del Rio

def moving_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2])
# and each end subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]))
# Author: Joe Kington / Erik Rigtorp

from numpy.lib import stride_tricks

def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace?
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.61203784, -0.29097382, -0.6934161 , -0.01323629, -0.29442477,
        0.23963033, -0.22226193,  0.35601958,  0.48371757,  0.53398636,
       -0.50934294,  0.50768161,  0.15561137, -0.15409346, -0.65112746,
       -0.37744204,  0.26708508,  0.11228892,  0.31377959,  0.71331309,
        0.19278053, -0.86881481,  0.72289148, -0.66606095,  0.7621094 ,
       -0.41597817,  0.97626635,  0.23348007, -0.231715  , -0.45774825,
        0.76342663, -0.53038559, -0.73928087, -0.09769654, -0.98801697,
        0.44444826,  0.66461768, -0.65860034, -0.30201019,  0.32380555,
       -0.23736878,  0.026365  ,  0.71736931,  0.69117886,  0.79375539,
        0.57309566, -0.64188138, -0.47203761,  0.74864674, -0.36330895,
       -0.80552386, -0.00366996, -0.85632348, -0.34056147,  0.64656188,
       -0.76594292, -0.18982262,  0.4573423 , -0.94898712,  0.17986113,
        0.28164133,  0.69471036, -0.26935009, -0.27288312,  0.19469986,
       -0.07213298, -0.64814492,  0.86185395,  0.45819305, -0.42

In [ ]:
# 78. Cosider 2 sets of points P0,P1 describing lines (2d) and point p, how to compute distance from p to each line i
# (P0[i],P1[i])?

def distance(P0, P1, p):
  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 0.43164318 12.63028768  9.12587225  8.88996745  0.7811208  12.62077045
  3.83793154 14.32444721  6.22939622  9.22912742]


In [ ]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j
# (P[j] to each line i (P0[i],P1[i]))?
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p  = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[2.85288684e+00 2.92059397e+00 1.04204127e+01 1.14443263e-02
  4.09484706e+00 1.00445635e+01 1.43837312e+00 4.55670203e+00
  3.08858546e+00 6.21497610e-01]
 [1.87363619e+00 4.30961429e+00 9.61142181e+00 8.17307309e+00
  1.42349136e+01 1.71408323e+01 7.29713565e+00 1.35832209e+00
  5.31622133e-01 9.35929851e+00]
 [1.10459835e+01 8.65434614e+00 3.16452672e-01 8.65332917e+00
  4.35467300e+00 4.14716145e+00 6.53631512e+00 1.17236272e+01
  7.74190758e+00 2.86088940e+00]
 [1.65648876e+01 1.78215361e+01 1.92231185e+00 3.30613119e+00
  9.38691145e+00 4.82143626e+00 6.12815723e+00 1.89593132e+01
  1.69114487e+00 1.43070321e+01]
 [1.28171122e+01 9.39780524e+00 3.52305811e+00 1.21840196e+01
  5.71208450e+00 3.33944935e+00 9.94667348e+00 1.30477683e+01
  1.13310831e+01 2.76277461e+00]
 [1.21171530e+00 3.20370890e+00 9.89139446e+00 6.71717308e+00
  1.25699471e+01 1.60591192e+01 5.75636929e+00 4.87581327e-01
  2.10239779e-01 7.97546907e+00]
 [5.83710980e+00 7.51949049e+00 1.09917183e+01 5.25525839e

In [ ]:
# 80. Cibsuder an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given
# element (pad with a fill value when necessary)
# Author: Nicolas Rougier

import numpy as np

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs= np.array(list(R.shape)).astype(int)
Zs= np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop  = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop  = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start, stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start, stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print()
print(R)

[[2 2 9 6 5 0 6 5 8 8]
 [1 6 3 2 0 4 9 7 9 4]
 [0 6 4 5 0 7 2 4 5 8]
 [3 4 5 4 2 7 9 7 9 3]
 [8 3 0 5 3 5 4 8 9 5]
 [1 5 8 9 8 9 8 3 3 2]
 [0 0 2 1 8 3 8 6 9 2]
 [7 2 8 8 3 3 1 5 7 3]
 [1 2 7 4 6 1 6 5 2 8]
 [7 7 8 2 2 2 1 0 8 8]]

[[0 0 0 0 0]
 [0 2 2 9 6]
 [0 1 6 3 2]
 [0 0 6 4 5]
 [0 3 4 5 4]]


In [ ]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4],[2,3,4,5],[3,4,5,6],
# ....,[11,12,13,14]]?
# Author: Stefan Van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

In [ ]:
# 82. Compute a matrix rank
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)       # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [ ]:
# 83. How to find the most frequent value in an array

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


In [ ]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

In [ ]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i,j = index
    super(Symetric, self).__setitem__((i,j), value)
    super(Symetric, self).__setitem__((j,i), value)
    
def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  2  9  9 13]
 [ 2  8  7 11 15]
 [ 9  7  2 42  8]
 [ 9 11 42  3 12]
 [13 15  8 12  9]]


In [ ]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sume of the
# p matrix products at once? (result has shape (n,1))
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [ ]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
# Author: Robert Kern

Z = np.ones((16,16))
K = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], K), axis=0),
                   np.arange(0, Z.shape[1], K), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
# 88. How to implement the Game of Life using numpy arrays?
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
# 89. How to get the n largest values of an array

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print(Z[np.argsort(Z)[-n:]])

# Fast
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9997 9998 9999 9995]


In [ ]:
# 90. Given an arbitrary number of vectors, build the cartesian product(every combinations of every item)
# Author: Stefan Van der Walt

def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
    
  return ix

print(cartesian(([1,2,3], [4,5], [6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
# 91. How to create a record array from a regular array

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
# 92. Consider a larg vector Z, compute Z to the power of 3 using 3 different methods.
# Author: Ryan G.

x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
print(x)

In [ ]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B
# regardless of the order of the elements in B?
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)
print()
print(A)
print()
print(B)

[0 2 4 5]

[[1 4 0]
 [2 2 1]
 [4 0 3]
 [3 3 2]
 [3 3 1]
 [1 0 0]
 [3 2 0]
 [3 2 2]]

[[0 3]
 [1 4]]


In [ ]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e,g.[2,2,3])
# Author: Robert Kert

Z = np.random.randint(0,5,(10,3))
print(Z)
print()

# Solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
print()

# Solution for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 4]
 [2 0 3]
 [3 0 0]
 [2 4 4]
 [0 3 2]
 [3 2 2]
 [2 0 0]
 [3 0 1]
 [0 2 3]
 [1 0 1]]

[[1 0 4]
 [2 0 3]
 [3 0 0]
 [2 4 4]
 [0 3 2]
 [3 2 2]
 [2 0 0]
 [3 0 1]
 [0 2 3]
 [1 0 1]]

[[1 0 4]
 [2 0 3]
 [3 0 0]
 [2 4 4]
 [0 3 2]
 [3 2 2]
 [2 0 0]
 [3 0 1]
 [0 2 3]
 [1 0 1]]


In [ ]:
# 95. Convert a vector of ints into a matrix binary representation
# Author: Warren Weckesser

I = np.array([0,1,2,3,15,16,32,64,128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
print()

# Auther: Daniel T. McDonald
I = np.array([0,1,2,3,15,16,32,64,128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [ ]:
# 96. Given a two dimensional array, how to extract unique rows?
# Author: Jaime Fernandez del Rio

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
print()

# Author: Andreas Kouzelis
# Numpy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]]

[[0 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 1]]


In [ ]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
# Auther: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.02776685, 0.02531497, 0.0239223 , 0.01173566, 0.01284355,
        0.00415973, 0.00400533, 0.027874  , 0.00816466, 0.00094197],
       [0.90454074, 0.82466772, 0.77929983, 0.38230419, 0.41839509,
        0.13550849, 0.1304787 , 0.90803143, 0.26597427, 0.03068592],
       [0.83433422, 0.7606606 , 0.71881397, 0.3526314 , 0.38592108,
        0.12499091, 0.12035151, 0.83755397, 0.24533051, 0.02830422],
       [0.81611486, 0.74405005, 0.70311722, 0.34493098, 0.37749372,
        0.12226148, 0.11772339, 0.8192643 , 0.23997322, 0.02768614],
       [0.79345325, 0.72338951, 0.68359329, 0.33535305, 0.36701159,
        0.11886656, 0.11445448, 0.79651523, 0.23330972, 0.02691736],
       [0.63321889, 0.57730421, 0.54554466, 0.26762999, 0.29289523,
        0.09486199, 0.09134091, 0.63566253, 0.18619386, 0.02148152],
       [0.90623425, 0.82621169, 0.78075886, 0.38301995, 0.41917842,
        0.13576219, 0.13072298, 0.90973147, 0.26647224, 0.03074338],
       [0.54975931, 0.5012143 , 0.4736407

In [ ]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # Segment length
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)              # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)     # integrate path
y_int = np.interp(r_int, r, y)

In [ ]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from multinomial
# distribution with n degrees, i.e., the rows which only contain integers and which sum to n
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
               [2.0, 0.0, 1.0, 1.0],
               [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X(i.e., resample the elements of an array
# with replacement N times, compute the mean of each sample, and then compute percentiles over the mean)
# Author: Jessica B. Hamrick

X = np.random.randn(100)   # random 1D array
N = 1000                   # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.25782112  0.08256956]
