<a href="https://colab.research.google.com/github/AbdelnasserMostafa/-myproject/blob/master/Grid_Search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
cd Model_Selection/

/content/k-Fold/Model_Selection


In [ ]:
ls -la

total 36
drwxr-xr-x 2 root root  4096 Jan 30  2017 ./
drwxr-xr-x 4 root root  4096 Feb  7 22:46 ../
-rw-r--r-- 1 root root  3476 Jan  2  2017 grid_search.py
-rw-r--r-- 1 root root  3192 Jan 29  2017 grid_search.R
-rw-r--r-- 1 root root  2830 Dec 31  2016 k_fold_cross_validation.py
-rw-r--r-- 1 root root  2994 Jan 29  2017 k_fold_cross_validation.R
-rw-r--r-- 1 root root 10930 Sep 10  2016 Social_Network_Ads.csv


In [ ]:
# Grid Search

In [ ]:
# Import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [ ]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
5    15728773    Male  27.0          58000.0          0
6    15598044  Female  27.0          84000.0          0
7    15694829  Female  32.0         150000.0          1
8    15600575    Male  25.0          33000.0          0
9    15727311  Female  35.0          65000.0          0
10   15570769  Female  26.0          80000.0          0
11   15606274  Female  26.0          52000.0          0
12   15746139    Male  20.0          86000.0          0
13   15704987    Male  32.0          18000.0          0
14   15628972    Male  18.0          82000.0          0
15   15697686    Male  29.0          80000.0          0
16   15733883    Male  47.0          25000.0          1
17   15617482    Male  45.0          26000.0          1
18   15704583    Male  46.0          28000.0          1
19   15621083  Female  48.0          29000.0          1
20   15649487    Male  45.0          22000.0          1
21   15736760  Female  47.0          49000.0          1
22   15714658    Male  48.0          41000.0          1
23   15599081  Female  45.0          22000.0          1
24   15705113    Male  46.0          23000.0          1
25   15631159    Male  47.0          20000.0          1
26   15792818    Male  49.0          28000.0          1
27   15633531  Female  47.0          30000.0          1
28   15744529    Male  29.0          43000.0          0
29   15669656    Male  31.0          18000.0          0
..        ...     ...   ...              ...        ...
370  15611430  Female  60.0          46000.0          1
371  15774744    Male  60.0          83000.0          1
372  15629885  Female  39.0          73000.0          0
373  15708791    Male  59.0         130000.0          1
374  15793890  Female  37.0          80000.0          0
375  15646091  Female  46.0          32000.0          1
376  15596984  Female  46.0          74000.0          0
377  15800215  Female  42.0          53000.0          0
378  15577806    Male  41.0          87000.0          1
379  15749381  Female  58.0          23000.0          1
380  15683758    Male  42.0          64000.0          0
381  15670615    Male  48.0          33000.0          1
382  15715622  Female  44.0         139000.0          1
383  15707634    Male  49.0          28000.0          1
384  15806901  Female  57.0          33000.0          1
385  15775335    Male  56.0          60000.0          1
386  15724150  Female  49.0          39000.0          1
387  15627220    Male  39.0          71000.0          0
388  15672330    Male  47.0          34000.0          1
389  15668521  Female  48.0          35000.0          1
390  15807837    Male  48.0          33000.0          1
391  15592570    Male  47.0          23000.0          1
392  15748589  Female  45.0          45000.0          1
393  15635893    Male  60.0          42000.0          1
394  15757632  Female  39.0          59000.0          0
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [ ]:
X

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
# Splitting the dataset into the Training set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,
                                                   random_state = 0)

In [ ]:
X_train

array([[4.40e+01, 3.90e+04],
       [3.20e+01, 1.20e+05],
       [3.80e+01, 5.00e+04],
       [3.20e+01, 1.35e+05],
       [5.20e+01, 2.10e+04],
       [5.30e+01, 1.04e+05],
       [3.90e+01, 4.20e+04],
       [3.80e+01, 6.10e+04],
       [3.60e+01, 5.00e+04],
       [3.60e+01, 6.30e+04],
       [3.50e+01, 2.50e+04],
       [3.50e+01, 5.00e+04],
       [4.20e+01, 7.30e+04],
       [4.70e+01, 4.90e+04],
       [5.90e+01, 2.90e+04],
       [4.90e+01, 6.50e+04],
       [4.50e+01, 1.31e+05],
       [3.10e+01, 8.90e+04],
       [4.60e+01, 8.20e+04],
       [4.70e+01, 5.10e+04],
       [2.60e+01, 1.50e+04],
       [6.00e+01, 1.02e+05],
       [3.80e+01, 1.12e+05],
       [4.00e+01, 1.07e+05],
       [4.20e+01, 5.30e+04],
       [3.50e+01, 5.90e+04],
       [4.80e+01, 4.10e+04],
       [4.80e+01, 1.34e+05],
       [3.80e+01, 1.13e+05],
       [2.90e+01, 1.48e+05],
       [2.60e+01, 1.50e+04],
       [6.00e+01, 4.20e+04],
       [2.40e+01, 1.90e+04],
       [4.20e+01, 1.49e+05],
       [4.60e+

In [ ]:
X_test

array([[3.00e+01, 8.70e+04],
       [3.80e+01, 5.00e+04],
       [3.50e+01, 7.50e+04],
       [3.00e+01, 7.90e+04],
       [3.50e+01, 5.00e+04],
       [2.70e+01, 2.00e+04],
       [3.10e+01, 1.50e+04],
       [3.60e+01, 1.44e+05],
       [1.80e+01, 6.80e+04],
       [4.70e+01, 4.30e+04],
       [3.00e+01, 4.90e+04],
       [2.80e+01, 5.50e+04],
       [3.70e+01, 5.50e+04],
       [3.90e+01, 7.70e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.17e+05],
       [3.70e+01, 7.70e+04],
       [1.90e+01, 8.50e+04],
       [5.50e+01, 1.30e+05],
       [3.50e+01, 2.20e+04],
       [3.50e+01, 4.70e+04],
       [4.70e+01, 1.44e+05],
       [4.10e+01, 5.10e+04],
       [4.70e+01, 1.05e+05],
       [2.30e+01, 2.80e+04],
       [4.90e+01, 1.41e+05],
       [2.80e+01, 8.70e+04],
       [2.90e+01, 8.00e+04],
       [3.70e+01, 6.20e+04],
       [3.20e+01, 8.60e+04],
       [2.10e+01, 8.80e+04],
       [3.70e+01, 7.90e+04],
       [5.70e+01, 6.00e+04],
       [3.70e+01, 5.30e+04],
       [2.40e+

In [ ]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

In [ ]:
X_test

array([[-0.80480212,  0.50496393],
       [-0.01254409, -0.5677824 ],
       [-0.30964085,  0.1570462 ],
       [-0.80480212,  0.27301877],
       [-0.30964085, -0.5677824 ],
       [-1.10189888, -1.43757673],
       [-0.70576986, -1.58254245],
       [-0.21060859,  2.15757314],
       [-1.99318916, -0.04590581],
       [ 0.8787462 , -0.77073441],
       [-0.80480212, -0.59677555],
       [-1.00286662, -0.42281668],
       [-0.11157634, -0.42281668],
       [ 0.08648817,  0.21503249],
       [-1.79512465,  0.47597078],
       [-0.60673761,  1.37475825],
       [-0.11157634,  0.21503249],
       [-1.89415691,  0.44697764],
       [ 1.67100423,  1.75166912],
       [-0.30964085, -1.37959044],
       [-0.30964085, -0.65476184],
       [ 0.8787462 ,  2.15757314],
       [ 0.28455268, -0.53878926],
       [ 0.8787462 ,  1.02684052],
       [-1.49802789, -1.20563157],
       [ 1.07681071,  2.07059371],
       [-1.00286662,  0.50496393],
       [-0.90383437,  0.30201192],
       [-0.11157634,

In [ ]:
# Fitting The Classifier to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [ ]:
classifier

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

array([[64,  4],
       [ 3, 29]])

In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default 

0.06388957356626285

In [ ]:
accuracies

array([0.80645161, 0.96666667, 0.8       , 0.93333333, 0.86666667,
       0.83333333, 0.93333333, 0.93333333, 0.96666667, 0.96551724])

In [ ]:
accuracies.mean()

0.9005302187615868

In [ ]:
accuracies.std()

0.06388957356626285

In [ ]:
# Improving the Model Performance
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV

# you can modify these values to get the best parameters for your model
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.5, 0.1, 0.01, 0.001, 0.0001]}]
grid_search = GridSearchCV(estimator = classifier,
                         param_grid = parameters,
                         scoring = 'accuracy',
                         cv = 10,
                         n_jobs = -1) # for big dataset modify this value
grid_search = grid_search.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [ ]:
parameters

[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
 {'C': [1, 10, 100, 1000],
  'gamma': [0.5, 0.1, 0.01, 0.001, 0.0001],
  'kernel': ['rbf']}]

In [ ]:
grid_search

GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.5, 0.1, 0.01, 0.001, 0.0001]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [ ]:
# Get the best accuracy score
best_accuracy = grid_search.best_score_

In [ ]:
best_accuracy

0.9

In [ ]:
# Get thes paramater(what are they)? to get the best values (parameters) for your model
best_parameters = grid_search.best_params_

In [ ]:
best_parameters

{'C': 1, 'gamma': 0.5, 'kernel': 'rbf'}