<a href="https://colab.research.google.com/github/AbdelnasserMostafa/-myproject/blob/master/GXBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget http://www.superdatascience.com/wp-content/uploads/2017/02/XGBoost.zip

--2019-02-08 02:06:05--  http://www.superdatascience.com/wp-content/uploads/2017/02/XGBoost.zip
Resolving www.superdatascience.com (www.superdatascience.com)... 104.27.172.21, 104.27.173.21, 2606:4700:30::681b:ac15, ...
Connecting to www.superdatascience.com (www.superdatascience.com)|104.27.172.21|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.superdatascience.com/wp-content/uploads/2017/02/XGBoost.zip [following]
--2019-02-08 02:06:06--  https://www.superdatascience.com/wp-content/uploads/2017/02/XGBoost.zip
Connecting to www.superdatascience.com (www.superdatascience.com)|104.27.172.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 267483 (261K) [application/zip]
Saving to: ‘XGBoost.zip’

XGBoost.zip         100%[===================>] 261.21K  1.17MB/s    in 0.2s    

2019-02-08 02:06:06 (1.17 MB/s) - ‘XGBoost.zip’ saved [267483/267483]



In [ ]:
ls -la

total 304
drwxr-xr-x 1 root root   4096 Feb  8 02:06 ./
drwxr-xr-x 1 root root   4096 Feb  7 22:43 ../
drwxr-xr-x 4 root root   4096 Feb  6 17:30 .config/
drwxr-xr-x 4 root root   4096 Feb  7 22:46 k-Fold/
-rw-r--r-- 1 root root  10573 Feb 17  2017 Model-Selection.zip
drwxr-xr-x 1 root root   4096 Feb  6 17:31 sample_data/
-rw-r--r-- 1 root root 267483 Feb 17  2017 XGBoost.zip


In [ ]:
!mkdir XGBoost

In [ ]:
!unzip XGBoost.zip -d XGBoost/

Archive:  XGBoost.zip
   creating: XGBoost/XGBoost/
  inflating: XGBoost/XGBoost/.DS_Store  
   creating: XGBoost/__MACOSX/
   creating: XGBoost/__MACOSX/XGBoost/
  inflating: XGBoost/__MACOSX/XGBoost/._.DS_Store  
  inflating: XGBoost/XGBoost/Churn_Modelling.csv  
  inflating: XGBoost/__MACOSX/XGBoost/._Churn_Modelling.csv  
  inflating: XGBoost/XGBoost/xgboost.py  
  inflating: XGBoost/__MACOSX/XGBoost/._xgboost.py  
  inflating: XGBoost/XGBoost/xgboost.R  
  inflating: XGBoost/__MACOSX/XGBoost/._xgboost.R  
  inflating: XGBoost/__MACOSX/._XGBoost  


In [ ]:
cd XGBoost/

/content/XGBoost


In [ ]:
ls -la

total 16
drwxr-xr-x 4 root root 4096 Feb  8 02:07 ./
drwxr-xr-x 1 root root 4096 Feb  8 02:06 ../
drwxrwxr-x 3 root root 4096 Jan 30  2017 __MACOSX/
drwxr-xr-x 2 root root 4096 Jan 30  2017 XGBoost/


In [ ]:
cd XGBoost/

/content/XGBoost/XGBoost


In [ ]:
ls -la

total 696
drwxr-xr-x 2 root root   4096 Jan 30  2017 ./
drwxr-xr-x 4 root root   4096 Feb  8 02:07 ../
-rw-r--r-- 1 root root 684858 Aug 28  2016 Churn_Modelling.csv
-rw-r--r-- 1 root root   6148 Jan 30  2017 .DS_Store
-rw-r--r-- 1 root root   1465 Jan  3  2017 xgboost.py
-rw-r--r-- 1 root root   1754 Jan 29  2017 xgboost.R


In [ ]:
# XGBoost

# Install xgboost followint the instruction on this link:
# http://xgboost.readthedocs.io/en/latest/build.html#

In [ ]:
# Importing the library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [ ]:
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [ ]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 6.6700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 4.2700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 5.3500000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [ ]:
X_test

array([[1.0000000e+00, 0.0000000e+00, 5.9700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.9285267e+05],
       [0.0000000e+00, 0.0000000e+00, 5.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.2870210e+05],
       [0.0000000e+00, 1.0000000e+00, 7.0600000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 7.5732250e+04],
       ...,
       [0.0000000e+00, 1.0000000e+00, 5.7800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.4153319e+05],
       [1.0000000e+00, 0.0000000e+00, 6.5000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.1276480e+04],
       [1.0000000e+00, 0.0000000e+00, 5.7300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.9295060e+05]])

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
# Installing XGBoost
!git clone --recursive https://github.com/dmlc/xgboost

Cloning into 'xgboost'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 26882 (delta 0), reused 0 (delta 0), pack-reused 26879
Receiving objects: 100% (26882/26882), 10.18 MiB | 20.20 MiB/s, done.
Resolving deltas: 100% (15783/15783), done.
Submodule 'cub' (https://github.com/NVlabs/cub) registered for path 'cub'
Submodule 'dmlc-core' (https://github.com/dmlc/dmlc-core) registered for path 'dmlc-core'
Submodule 'rabit' (https://github.com/dmlc/rabit) registered for path 'rabit'
Cloning into '/content/XGBoost/XGBoost/xgboost/cub'...
remote: Enumerating objects: 29, done.        
remote: Counting objects: 100% (29/29), done.        
remote: Compressing objects: 100% (27/27), done.        
remote: Total 32671 (delta 7), reused 22 (delta 2), pack-reused 32642        
Receiving objects: 100% (32671/32671), 16.57 MiB | 25.03 MiB/s, done.
Resolving deltas: 100% (28628/28628), done.
Cloning into '/

In [ ]:
!cd xgboost; make -j4

Makefile:31: MAKE [make] - checked OK
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/predictor/cpu_predictor.o src/predictor/cpu_predictor.cc >build/predictor/cpu_predictor.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
g++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/predictor/predictor.o src/predictor/predictor.cc >build/predictor/predic

In [ ]:
!pip3 install xgboost

In [ ]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


ImportError: ignored

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

NameError: ignored

In [ ]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
accuracies.mean()
accuracies.std()

NameError: ignored